---
title: IRisk Queue Project
author: Lucian

# Execution settings (whether to run notebooks when building)
execute:
  execute_notebooks: off  # 'off', 'auto', or 'force'

# HTML settings
html:
  use_repository_button: true
  use_issues_button: true
  baseurl: /lucians2_Queue_Project

repository:
  url: https://github.com/LucianJSlo/lucians2_Queue_Project